name: Build tests
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test-action:
    runs-on: ubuntu-latest
    name: "test-action"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - name: Edit readme
        uses: ./
        with:
          from_file: 'README.md'
          to_file: 'README.md'
          commit: 'false'
